# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 19:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='MPUser',
        ),
        migrations.CreateModel(
            name='MPUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
