# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20160217_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remembertoken',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='RememberToken',
        ),
    ]
