# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20160213_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='videos',
            field=models.ManyToManyField(blank=True, to='case.Video'),
        ),
    ]
