# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20160223_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('requester', models.IntegerField()),
                ('collection_id', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mediaqueue',
            },
        ),
        migrations.CreateModel(
            name='MediaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('original_url', models.CharField(max_length=255)),
                ('embed_url', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=8)),
                ('naughty', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mediastore',
            },
        ),
    ]
