# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_mediaqueue_mediastore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediaqueue',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
