# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0006_auto_20160213_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MPUser',
        ),
        migrations.AddField(
            model_name='invite',
            name='claimed_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 23, 20, 34, 246702, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 15, 23, 20, 48, 605816, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remembertoken',
            name='claimed_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 23, 21, 7, 813363, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remembertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 15, 23, 21, 12, 365098, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='case.Collection'),
        ),
    ]
