# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_userreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_url',
            field=models.URLField(max_length=100),
        ),
    ]
