# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20160317_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'verbose_name': 'Report (user reporting video)', 'verbose_name_plural': 'Reports (user reporting video)'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
