# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_auto_20160321_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='assignee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
