# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20160321_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'verbose_name': 'Report (from user on site)', 'verbose_name_plural': 'Reports (from user on site)'},
        ),
    ]
