# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_auto_20160521_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlockRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollectionBlockRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollectionFollowRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='usertocollectionrelationship',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='usertocollectionrelationship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertouserrelationship',
            name='who',
        ),
        migrations.RemoveField(
            model_name='usertouserrelationship',
            name='whom',
        ),
        migrations.AlterField(
            model_name='collection',
            name='related_users',
            field=models.ManyToManyField(through='case.UserCollectionFollowRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='related_collections',
            field=models.ManyToManyField(through='case.UserCollectionFollowRelationship', to='case.Collection'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='related_users',
            field=models.ManyToManyField(through='case.UserFollowRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserToCollectionRelationship',
        ),
        migrations.DeleteModel(
            name='UserToUserRelationship',
        ),
        migrations.AddField(
            model_name='userfollowrelationship',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowrelationship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercollectionfollowrelationship',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_followed', to='case.Collection'),
        ),
        migrations.AddField(
            model_name='usercollectionfollowrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercollectionblockrelationship',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_blocked', to='case.Collection'),
        ),
        migrations.AddField(
            model_name='usercollectionblockrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblockrelationship',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblockrelationship',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to=settings.AUTH_USER_MODEL),
        ),
    ]
