# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_auto_20160521_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userblockrelationship',
            options={'verbose_name': 'User <-> User (block) relationship', 'verbose_name_plural': 'User <-> User (block) relationships'},
        ),
        migrations.AlterModelOptions(
            name='usercollectionblockrelationship',
            options={'verbose_name': 'User <-> Collection (block) relationship', 'verbose_name_plural': 'User <-> Collection (block) relationships'},
        ),
        migrations.AlterModelOptions(
            name='usercollectionfollowrelationship',
            options={'verbose_name': 'User <-> Collection (follow) relationship', 'verbose_name_plural': 'User <-> Collection (follow) relationships'},
        ),
        migrations.AlterModelOptions(
            name='userfollowrelationship',
            options={'verbose_name': 'User <-> User (follow) relationship', 'verbose_name_plural': 'User <-> User (follow) relationships'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to='case.FacebookUser'),
        ),
    ]
