# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0017_auto_20160525_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookuser',
            options={'verbose_name': 'Related Facebook user', 'verbose_name_plural': 'Related Facebook users'},
        ),
    ]
