# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_auto_20160525_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
    ]
