# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0021_auto_20160530_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook', to=settings.AUTH_USER_MODEL),
        ),
    ]
