# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_video_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaqueue',
            options={'verbose_name': 'Queued video', 'verbose_name_plural': 'Queued videos'},
        ),
        migrations.AlterModelOptions(
            name='mediastore',
            options={'verbose_name': 'Stored video', 'verbose_name_plural': 'Stored videos'},
        ),
        migrations.AlterField(
            model_name='mediaqueue',
            name='hash',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='mediastore',
            name='hash',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
