# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0026_auto_20160807_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaqueue',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
